# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import numpy as np
from PyQt5 import QtCore, QtGui, QtWidgets
import tkinter as tk
from tkinter import filedialog
import cv2
import cv2 as cv

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 700)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(1, 1, 1, 1))
        self.textEdit.setObjectName("textEdit")
        self.groupButton = QtWidgets.QGroupBox(self.centralwidget)
        self.groupButton.setGeometry(QtCore.QRect(10, 20, 161, 511))
        self.groupButton.setObjectName("groupButton")
        self.pushButton = QtWidgets.QPushButton(self.groupButton)
        self.pushButton.setGeometry(QtCore.QRect(30, 20, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.OpenFile)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupButton)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 70, 91, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.Reverse_Image)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupButton)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 120, 91, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.logarit_transform)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupButton)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 170, 91, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupButton)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 220, 91, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupButton)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 270, 91, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.groupBox_OriImg = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_OriImg.setGeometry(QtCore.QRect(190, 20, 471, 271))
        self.groupBox_OriImg.setObjectName("groupBox_OriImg")
        self.label_3 = QtWidgets.QLabel(self.groupBox_OriImg)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 451, 241))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("2021-04-02_205149.png"))
        self.label_3.setObjectName("label_3")
        self.groupBox_ImgProcess = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_ImgProcess.setGeometry(QtCore.QRect(190, 300, 471, 221))
        self.groupBox_ImgProcess.setObjectName("groupBox_ImgProcess")
        self.label_2 = QtWidgets.QLabel(self.groupBox_ImgProcess)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 441, 191))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("2021-04-02_205149.png"))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Image = QtWidgets.QAction(MainWindow)
        self.actionOpen_Image.setObjectName("actionOpen_Image")
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupButton.setTitle(_translate("MainWindow", "Group Button"))
        self.pushButton.setText(_translate("MainWindow", "Open Image"))
        self.pushButton_2.setText(_translate("MainWindow", "Reverse Image"))
        self.pushButton_3.setText(_translate("MainWindow", "Logarit Transform"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.groupBox_OriImg.setTitle(_translate("MainWindow", "Original Image"))
        self.groupBox_ImgProcess.setTitle(_translate("MainWindow", "Image processed"))
        self.actionOpen_Image.setText(_translate("MainWindow", "Open Image"))

    def OpenFile(self):
        root = tk.Tk()
        root.withdraw()
        self.file_path = filedialog.askopenfilename()
        if(self.file_path):
            self.label_3.setPixmap(QtGui.QPixmap(self.file_path))
            self.textEdit.setText(self.file_path)
        else:
            self.label_3.setPixmap(QtGui.QPixmap("2021-04-02_205149.png"))
    def Reverse_Image(self):
        filepath = self.textEdit.toPlainText()
        if(filepath==""):
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Critical)
            msg.setText("Error!!!")
            msg.setInformativeText("Please! Choose an Image")
            msg.setWindowTitle("Error")
            msg.exec_()
        else:
            self.image = cv2.imread(filepath)
            self.reverse_img = 255 - self.image
            self.show_image(self.reverse_img)

    def logarit_transform(self):
        filepath = self.textEdit.toPlainText()
        if (filepath == ""):
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Critical)
            msg.setText("Error!!!")
            msg.setInformativeText("Please! Choose an Image")
            msg.setWindowTitle("Error")
            msg.exec_()
        else:
            self.image = cv.imread(filepath)
            c = 255 / np.log(1 + np.max(self.image))
            self.log_image = c * (np.log(self.image + 1))
            self.log_image = np.array(self.log_image, dtype=np.uint8)
            self.show_image(self.log_image)
    @QtCore.pyqtSlot()
    def show_image(self, img):
        self.image = img
        self.image = QtGui.QImage(self.image.data, self.image.shape[1], self.image.shape[0],
                                  QtGui.QImage.Format_RGB888).rgbSwapped()
        self.label_2.setPixmap(QtGui.QPixmap.fromImage(self.image))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
